
import java.util.Arrays;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author SHAHBAZ HUSSAIN
 */
public class LRC extends javax.swing.JFrame {

    int temp[];
    String book_name;
    String author_name;

    /**
     * Creates new form LRC
     */
    public LRC() {
        initComponents();
        jButton1.setVisible(false);
        jLabel4.setVisible(false);
        jLabel6.setVisible(false);
        jTextField1.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jTextArea2.setVisible(false);
        jScrollPane2.setVisible(false);
    }


    public String search(String t, String b, String p, int n, int m) {
        //System.out.println(t+"  "+p);
        temp = new int[m];
        form(m, p);
        int j = 0;
        int i = 0;
        while (i < n && j < m) {
            if (t.charAt(i) == p.charAt(j)) {
                i++;
                j++;
            } else if (t.charAt(i) != p.charAt(j) && j != 0) {
                j = temp[j - 1];
            } else {
                i++;   //If Character does not Match and j=0
            }
        }

        if (j == m) {
            //System.out.println(t + "\t  " + b);
            return (t + "\t  " + b + "\n\n");
        }
        else
         return("\t\tNO MATCH FOUND!");
        
       }

    public void form(int m, String p) {
        int j = 0;
        temp[j] = 0;
        for (int i = 1; i < m;) {
            if (p.charAt(i) == p.charAt(j)) {
                temp[i] = j + 1;
                j++;
                i++;
            } else if (p.charAt(i) != p.charAt(j) && j == 0) {
                temp[i] = 0;
                i++;
            } else if (p.charAt(i) != p.charAt(j) && j != 0) {
                j = temp[j - 1];
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Enter Name or Initials of the Book");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 340, -1));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 110, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 90, -1));

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 70, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter Name or Initials of the Author");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 440, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 600, 220));

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 523, 100, 30));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.setOpaque(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 220, -1));

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("Book Name");
        jRadioButton5.setDoubleBuffered(true);
        jRadioButton5.setOpaque(false);
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, -1, -1));

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Aurthor Name");
        jRadioButton4.setOpaque(false);
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Search By ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 150, -1));

        jButton5.setText("NEXT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 523, 90, 30));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Maths");
        jRadioButton1.setOpaque(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 90, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Physics");
        jRadioButton2.setOpaque(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 120, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Computer Science");
        jRadioButton3.setOpaque(false);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 160, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Choose the Department");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 260, -1));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("                 LEARNING   RESOURCE   CENTER");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 600, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 870, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:

        if (jRadioButton1.isSelected() || jRadioButton2.isSelected() || jRadioButton3.isSelected()) {
            jRadioButton1.setVisible(false);
            jRadioButton2.setVisible(false);
            jRadioButton3.setVisible(false);
            jRadioButton4.setVisible(false);
            jRadioButton5.setVisible(false);
            jButton4.setVisible(false);
            jButton5.setVisible(false);
            jLabel3.setVisible(false);
            jLabel5.setVisible(false);
            jButton1.setVisible(true);
            jLabel6.setVisible(true);
            jTextField1.setVisible(true);
            jButton2.setVisible(true);
            jButton3.setVisible(true);
            jTextArea2.setVisible(true);
            jScrollPane2.setVisible(true);
        }
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int i;
        jTextArea2.setText("");
        LRC maths[] = new LRC[11];
        for (i = 0; i < 11; i++) {
            maths[i] = new LRC();
        }

        LRC physics[] = new LRC[11];
        for (i = 0; i < 11; i++) {
            physics[i] = new LRC();
        }

        LRC cs[] = new LRC[11];
        for (i = 0; i < 11; i++) {
            cs[i] = new LRC();
        }

        //INITIALIZATION STARTS
        maths[0].book_name = "HIGHER ENGINEERING MATHEMATICS";
        maths[0].author_name = "DR. B.S GREWAL";

        maths[1].book_name = "HIGHER ENGINEERING MATHEMATICS(ORIGINALS)";
        maths[1].author_name = "RAMANA";

        maths[2].book_name = "HIGHER MATHEMATICS FOR PHYSICS AND ENGINEERING";
        maths[2].author_name = "SHIMA";

        maths[3].book_name = "A TEXTBOOK OF HIGHER ENGINEERING MATHEMATICS SEM-III";
        maths[3].author_name = "N.P BALI";

        maths[4].book_name = "A TEXTBOOK OF HIGHER ENGINEERING MATHEMATICS SEM-IV";
        maths[4].author_name = "N.P BALI";

        maths[5].book_name = "COMPREHENSIVE HIGHER ENGINEERING MATHEMATICS(PTU, SEM-III)";
        maths[5].author_name = "N.P BALI";

        maths[6].book_name = "PROBLMS AND SOLUTIONS IN HIGHER ENGINEERING MATHEMATICS VOL-III";
        maths[6].author_name = "DR T.C GUPTA";

        maths[7].book_name = "A TEXTBOOK OF HIGHER ENGINEERING MATHEMATICS (PTU- JALANDHAR) SEM-IV";
        maths[7].author_name = "N.P BALI";

        maths[8].book_name = "HIGHER ENGINEERING MATHEMATICS";
        maths[8].author_name = "H.S GOVINDA RAO";

        maths[9].book_name = "PROBLMS AND SOLUTIONS IN HIGHER ENGINEERING MATHEMATICS VOL-II";
        maths[9].author_name = "DR. T.C GUPTA";

        maths[10].book_name = "PROBLMS AND SOLUTIONS IN HIGHER ENGINEERING MATHEMATICS VOL-I";
        maths[10].author_name = "DR. T.C GUPTA";

        //INITIALIZATION STARTS
        physics[0].book_name = "ENGINEERING PHYSICS";
        physics[0].author_name = "D.C GHOSH";

        physics[1].book_name = "ENGINEERING PHYSICS- II";
        physics[1].author_name = "NARINDAR KUMAR";

        physics[2].book_name = "ENGINEERING PHYSICS AND CHEMISTRY";
        physics[2].author_name = "SUBHASH CHANDRA";

        physics[3].book_name = "ENGINEERING PHYSICS PRACTICAL";
        physics[3].author_name = "DR. B. SRINIVASA RAO";

        physics[4].book_name = "ENGINEERING MECHANICS";
        physics[4].author_name = "H.M RAGHUNATH";

        physics[5].book_name = "ENGINEERING APPLIED PHYSICS";
        physics[5].author_name = "S.B JHA & RAO";

        physics[6].book_name = "THE FUNDAMENTALS OF ENGINEERING PHYSICS";
        physics[6].author_name = "DR PURNIMA SWARUP KHARE";

        physics[7].book_name = "A TEXTBOOK FOR ENGINEERING PHYSICS PRACTICAL";
        physics[7].author_name = "DR. RUBY DAS";

        physics[8].book_name = "OBJECTIVE PHYSICS";
        physics[8].author_name = "S.O PILLAI";

        //INITIALIZATION STARTS
        cs[0].book_name = "INTRODUCTION TO ALGORITHMS";
        cs[0].author_name = "T.H CORMEN";

        cs[1].book_name = "ALGORITHM DESIGN";
        cs[1].author_name = "J.KLEINBERG";

        cs[2].book_name = "DATA STRUCTURES AND THEIR ALGORITHMS";
        cs[2].author_name = "R.LEWIS";

        cs[3].book_name = "ALGORITHMIC GRAPGH THEORY";
        cs[3].author_name = "A.GIBBONS";

        cs[4].book_name = "THE C PROGRAMMING LANGUAGE ";
        cs[4].author_name = "BRIAN W. KERNIGHAN";

        cs[5].book_name = "DATA STRUCTURES";
        cs[5].author_name = "SEYMOUR LIPSCHUTZ";

        cs[6].book_name = "FUNDAMENTALS OF THE DATA STRUCTURES IN C";
        cs[6].author_name = "ELLIS HOROWITZ";

        cs[7].book_name = "FUNDAMENTALS OF SOFTWARE ENGINEERING";
        cs[7].author_name = "RAJIB MALL";

        cs[8].book_name = "SOFTWARE ENGINEERING: A PRACTIONERS APPROACH";
        cs[8].author_name = "ROGER S. PRESSMAN";

        cs[9].book_name = "SOFTWARE ENGINEERING";
        cs[9].author_name = "IAN SOMMERVILLE";

        int count=0;
        String pattern = jTextField1.getText();
        pattern=pattern.toUpperCase();
        int m = pattern.length();
        String abc;
        if (jRadioButton1.isSelected() && jRadioButton4.isSelected()) {
            for (i = 0; i < 11; i++) {
                int n = maths[i].author_name.length();
                abc = maths[i].search(maths[i].author_name, maths[i].book_name, pattern, n, m);
                if(abc.equals("\t\tNO MATCH FOUND!"))
                {
                    count++;
                }
                if(abc.equals("\t\tNO MATCH FOUND!") && count==11)
                {
                    jTextArea2.setText(abc);
                    count=0;
                }
                else if(!abc.equals("\t\tNO MATCH FOUND!"))
                jTextArea2.append(abc);
            }
            
        } else if (jRadioButton2.isSelected() && jRadioButton4.isSelected()) {
            for (i = 0; i < 9; i++) {
                int n = physics[i].author_name.length();
                abc = physics[i].search(physics[i].author_name, physics[i].book_name, pattern, n, m);
                if(abc.equals("\t\tNO MATCH FOUND!"))
                {
                    count++;
                }
                if(abc.equals("\t\tNO MATCH FOUND!") && count==9)
                {
                    jTextArea2.setText(abc);
                    count=0;
                }
                else if(!abc.equals("\t\tNO MATCH FOUND!"))
                jTextArea2.append(abc);
            }

        } else if (jRadioButton3.isSelected() && jRadioButton4.isSelected()) {
            for (i = 0; i < 10; i++) {
                int n = cs[i].author_name.length();
                abc = cs[i].search(cs[i].author_name, cs[i].book_name, pattern, n, m);
                if(abc.equals("\t\tNO MATCH FOUND!"))
                {
                    count++;
                }
                if(abc.equals("\t\tNO MATCH FOUND!") && count==10)
                {
                    jTextArea2.setText(abc);
                    count=0;
                }
                else if(!abc.equals("\t\tNO MATCH FOUND!"))
                jTextArea2.append(abc);
            }
        } else if (jRadioButton1.isSelected() && jRadioButton5.isSelected()) {
            for (i = 0; i < 11; i++) {
                int n = maths[i].book_name.length();
                abc = maths[i].search(maths[i].book_name, maths[i].author_name, pattern, n, m);
                if(abc.equals("\t\tNO MATCH FOUND!"))
                {
                    count++;
                }
                if(abc.equals("\t\tNO MATCH FOUND!") && count==11)
                {
                    jTextArea2.setText(abc);
                    count=0;
                }
                else if(!abc.equals("\t\tNO MATCH FOUND!"))
                jTextArea2.append(abc);
            }

        } else if (jRadioButton2.isSelected() && jRadioButton5.isSelected()) {
            for (i = 0; i < 9; i++) {
                int n = physics[i].book_name.length();
                abc = physics[i].search(physics[i].book_name, physics[i].author_name, pattern, n, m);
                if(abc.equals("\t\tNO MATCH FOUND!"))
                {
                    count++;
                }
                if(abc.equals("\t\tNO MATCH FOUND!") && count==9)
                {
                    jTextArea2.setText(abc);
                    count=0;
                }
                else if(!abc.equals("\t\tNO MATCH FOUND!"))
                jTextArea2.append(abc);
            }

        } else if (jRadioButton3.isSelected() && jRadioButton5.isSelected()) {
            for (i = 0; i < 10; i++) {
                int n = cs[i].book_name.length();
                abc = cs[i].search(cs[i].book_name, cs[i].author_name, pattern, n, m);
                if(abc.equals("\t\tNO MATCH FOUND!"))
                {
                    count++;
                }
                if(abc.equals("\t\tNO MATCH FOUND!") && count==10)
                {
                    jTextArea2.setText(abc);
                    count=0;
                }
                else if(!abc.equals("\t\tNO MATCH FOUND!"))
                jTextArea2.append(abc);
            }

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:

        if (jRadioButton1.isSelected() || jRadioButton2.isSelected() || jRadioButton3.isSelected()) {
            jRadioButton1.setVisible(false);
            jRadioButton2.setVisible(false);
            jRadioButton3.setVisible(false);
            jRadioButton4.setVisible(false);
            jRadioButton5.setVisible(false);
            jButton4.setVisible(false);
            jButton5.setVisible(false);
            jLabel3.setVisible(false);
            jLabel5.setVisible(false);
            jButton1.setVisible(true);
            jLabel4.setVisible(true);
            jTextField1.setVisible(true);
            jButton2.setVisible(true);
            jButton3.setVisible(true);
            jTextArea2.setVisible(true);
            jScrollPane2.setVisible(true);
        }
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jRadioButton1.setVisible(true);
        jRadioButton2.setVisible(true);
        jRadioButton3.setVisible(true);
        jRadioButton4.setVisible(true);
        jRadioButton5.setVisible(true);
        jButton4.setVisible(true);
        jButton5.setVisible(true);
        jLabel3.setVisible(true);
        jLabel5.setVisible(true);
        jButton1.setVisible(false);
        jLabel4.setVisible(false);
        jLabel6.setVisible(false);
        jTextField1.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jTextArea2.setVisible(false);
        jScrollPane2.setVisible(false);
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        jTextArea2.setText("");
        jTextField1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:

        if (jRadioButton4.isSelected() || jRadioButton5.isSelected()) {
            jRadioButton1.setVisible(false);
            jRadioButton2.setVisible(false);
            jRadioButton3.setVisible(false);
            jRadioButton4.setVisible(false);
            jRadioButton5.setVisible(false);
            jButton4.setVisible(false);
            jButton5.setVisible(false);
            jLabel3.setVisible(false);
            jLabel5.setVisible(false);
            jButton1.setVisible(true);
            if (jRadioButton4.isSelected()) {
                jLabel4.setVisible(true);
            } else {
                jLabel6.setVisible(true);
            }
            jTextField1.setVisible(true);
            jButton2.setVisible(true);
            jButton3.setVisible(true);
            jTextArea2.setVisible(true);
            jScrollPane2.setVisible(true);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton4.isSelected() || jRadioButton5.isSelected()) {
            jRadioButton1.setVisible(false);
            jRadioButton2.setVisible(false);
            jRadioButton3.setVisible(false);
            jRadioButton4.setVisible(false);
            jRadioButton5.setVisible(false);
            jButton4.setVisible(false);
            jButton5.setVisible(false);
            jLabel3.setVisible(false);
            jLabel5.setVisible(false);
            jButton1.setVisible(true);
            if (jRadioButton4.isSelected()) {
                jLabel4.setVisible(true);
            } else {
                jLabel6.setVisible(true);
            }
            jTextField1.setVisible(true);
            jButton2.setVisible(true);
            jButton3.setVisible(true);
            jTextArea2.setVisible(true);
            jScrollPane2.setVisible(true);
        }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton4.isSelected() || jRadioButton5.isSelected()) {
            jRadioButton1.setVisible(false);
            jRadioButton2.setVisible(false);
            jRadioButton3.setVisible(false);
            jRadioButton4.setVisible(false);
            jRadioButton5.setVisible(false);
            jButton4.setVisible(false);
            jButton5.setVisible(false);
            jLabel3.setVisible(false);
            jLabel5.setVisible(false);
            jButton1.setVisible(true);
            if (jRadioButton4.isSelected()) {
                jLabel4.setVisible(true);
            } else {
                jLabel6.setVisible(true);
            }
            jTextField1.setVisible(true);
            jButton2.setVisible(true);
            jButton3.setVisible(true);
            jTextArea2.setVisible(true);
            jScrollPane2.setVisible(true);
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextArea2.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Map().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Last().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LRC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LRC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LRC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LRC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LRC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
